from enum import Enum

class MessageType(Enum):
    DEFAULT = 0
    RECIPIENT_ADD = 1
    RECIPIENT_REMOVE = 2
    CALL = 3
    CHANNEL_NAME_CHANGE = 4
    CHANNEL_ICON_CHANGE = 5
    CHANNEL_PINNED_MESSAGE = 6
    USER_JOIN = 7
    GUILD_BOOST = 8
    GUILD_BOOST_TIER_1 = 9
    GUILD_BOOST_TIER_2 = 10
    GUILD_BOOST_TIER_3 = 11
    CHANNEL_FOLLOW_ADD = 12
    GUILD_DISCOVERY_DISQUALIFIED = 14
    GUILD_DISCOVERY_REQUALIFIED = 15
    GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING = 16
    GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING = 17
    THREAD_CREATED = 18
    REPLY = 19
    CHAT_INPUT_COMMAND = 20
    THREAD_STARTER_MESSAGE = 21
    GUILD_INVITE_REMINDER = 22
    CONTEXT_MENU_COMMAND = 23
    AUTO_MODERATION_ACTION = 24
    ROLE_SUBSCRIPTION_PURCHASE = 25
    INTERACTION_PREMIUM_UPSELL = 26
    STAGE_START = 27
    STAGE_END = 28
    STAGE_SPEAKER = 29
    STAGE_TOPIC = 31
    GUILD_APPLICATION_PREMIUM_SUBSCRIPTION = 32
    GUILD_INCIDENT_ALERT_MODE_ENABLED = 36
    GUILD_INCIDENT_ALERT_MODE_DISABLED = 37
    GUILD_INCIDENT_REPORT_RAID = 38
    GUILD_INCIDENT_REPORT_FALSE_ALARM = 39
    PURCHASE_NOTIFICATION = 44
    POLL_RESULT = 46

# Deletable status for each message type
DELETABLE_MESSAGE_TYPES = {
    MessageType.DEFAULT,
    MessageType.CHANNEL_PINNED_MESSAGE,
    MessageType.USER_JOIN,
    MessageType.GUILD_BOOST,
    MessageType.GUILD_BOOST_TIER_1,
    MessageType.GUILD_BOOST_TIER_2,
    MessageType.GUILD_BOOST_TIER_3,
    MessageType.CHANNEL_FOLLOW_ADD,
    MessageType.GUILD_DISCOVERY_DISQUALIFIED,
    MessageType.GUILD_DISCOVERY_REQUALIFIED,
    MessageType.GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING,
    MessageType.GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING,
    MessageType.THREAD_CREATED,
    MessageType.REPLY,
    MessageType.CHAT_INPUT_COMMAND,
    MessageType.GUILD_INVITE_REMINDER,
    MessageType.CONTEXT_MENU_COMMAND,
    MessageType.AUTO_MODERATION_ACTION,
    MessageType.ROLE_SUBSCRIPTION_PURCHASE,
    MessageType.INTERACTION_PREMIUM_UPSELL,
    MessageType.STAGE_START,
    MessageType.STAGE_END,
    MessageType.STAGE_SPEAKER,
    MessageType.STAGE_TOPIC,
    MessageType.GUILD_APPLICATION_PREMIUM_SUBSCRIPTION,
    MessageType.GUILD_INCIDENT_ALERT_MODE_ENABLED,
    MessageType.GUILD_INCIDENT_ALERT_MODE_DISABLED,
    MessageType.GUILD_INCIDENT_REPORT_RAID,
    MessageType.GUILD_INCIDENT_REPORT_FALSE_ALARM,
    MessageType.PURCHASE_NOTIFICATION,
    MessageType.POLL_RESULT,
}

def is_deletable(message_type: MessageType) -> bool:
    return message_type in DELETABLE_MESSAGE_TYPES